INSERT INTO "Categories" ("Id", "Name") VALUES ('1', 'Дорогие');
INSERT INTO "Categories" ("Id", "Name") VALUES ('2', 'Дешёвые');
INSERT INTO "Categories" ("Id", "Name") VALUES ('3', 'Полезные');
INSERT INTO "Categories" ("Id", "Name") VALUES ('4', 'Овощи');
INSERT INTO "Categories" ("Id", "Name") VALUES ('5', 'Фрукты');
INSERT INTO "Categories" ("Id", "Name") VALUES ('6', 'Конфеты');
INSERT INTO "Products" ("Id", "Name") VALUES ('1', 'Мандарины Маркет');
INSERT INTO "Products" ("Id", "Name") VALUES ('2', 'Мандарины Выгодно');
INSERT INTO "Products" ("Id", "Name") VALUES ('3', 'Вода Aqua Minerale');
INSERT INTO "Products" ("Id", "Name") VALUES ('4', 'Напиток газинорванны Pepsi Max');
INSERT INTO "Products" ("Id", "Name") VALUES ('5', 'Квас Русский дар');
INSERT INTO "Products" ("Id", "Name") VALUES ('6', 'Стейк из семги замороженного сырья');
INSERT INTO "Products" ("Id", "Name") VALUES ('7', 'Тушка цыплёнка-бройлера Петруха');
INSERT INTO "Products" ("Id", "Name") VALUES ('8', 'Колбаса варённая Вязанка Докторская ГОСТ');
INSERT INTO "Products" ("Id", "Name") VALUES ('9', 'Печенье Юбилейное молочное');
INSERT INTO "ProductCategories" ("Product_Id", "Category_Id") VALUES ('1', '5');
INSERT INTO "ProductCategories" ("Product_Id", "Category_Id") VALUES ('2', '5');
INSERT INTO "ProductCategories" ("Product_Id", "Category_Id") VALUES ('6', '1');
INSERT INTO "ProductCategories" ("Product_Id", "Category_Id") VALUES ('2', '2');